"use client";

import React, { useState } from 'react';
import { X, Download, Share2, Copy, Check, Eye, FileArchive, User, Sparkles } from 'lucide-react';
import { AssetPoster } from '../types';

interface PosterDetailModalProps {
  poster: AssetPoster | null;
  onClose: () => void;
  onDownload: (poster: AssetPoster) => void;
}

export const PosterDetailModal: React.FC<PosterDetailModalProps> = ({
  poster,
  onClose,
  onDownload,
}) => {
  const [copied, setCopied] = useState(false);

  if (!poster) return null;

  const handleCopyAlt = () => {
    navigator.clipboard.writeText(poster.dataAlt);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadFile = (url: string, filename: string) => {
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.target = '_blank';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const FALLBACK_TEMPLATE_IMAGE = "http://localhost:8000/templates/diwali/diwali01/template.png";

  return (
    <div className="fixed inset-0 z-50 bg-black/75 backdrop-blur-xs flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-white rounded-2xl max-w-4xl w-full border border-[#DDE3EE] shadow-2xl overflow-hidden animate-fade-in my-6">
        {/* Header */}
        <div className="bg-[#0D1B3E] text-white p-4 px-6 flex justify-between items-center">
          <div className="flex items-center gap-2">
            <Eye className="w-5 h-5 text-amber-300" />
            <h3 className="font-bold text-base truncate max-w-md">{poster.filename}</h3>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 hover:bg-white/10 rounded-full transition-all text-white/80 hover:text-white cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 p-6 max-h-[75vh] overflow-y-auto">
          {/* Left: Media Display (Poster Image or Bulk First Poster Preview) */}
          <div className="flex flex-col items-center justify-center bg-[#0D1B3E] rounded-xl p-4 border border-[#DDE3EE] min-h-[360px] relative overflow-hidden">
            <img
              src={poster.imageUrl || FALLBACK_TEMPLATE_IMAGE}
              alt={poster.dataAlt}
              className="max-h-[440px] w-auto object-contain rounded-lg shadow-2xl"
              onError={(e) => {
                const target = e.target as HTMLImageElement;
                if (target.src !== FALLBACK_TEMPLATE_IMAGE) {
                  target.src = FALLBACK_TEMPLATE_IMAGE;
                }
              }}
            />

            {poster.isBulk && (
              <div className="absolute top-3 left-3 bg-[#0D1B3E]/90 text-amber-300 text-[10px] font-bold px-3 py-1 rounded-full border border-amber-400/40 backdrop-blur-md">
                ✦ TEMPLATE USED FOR BULK JOB ({poster.templateFolder || 'Template Asset'})
              </div>
            )}
          </div>

          {/* Right: Asset Metadata & Authorship Details */}
          <div className="flex flex-col justify-between space-y-6">
            <div className="space-y-4">
              <div>
                <span className="text-[10px] font-bold uppercase tracking-wider text-[#0D1B3E] bg-[#f5f3f6] border border-[#DDE3EE] px-2.5 py-1 rounded-md">
                  Single Poster Output
                </span>
                <h2 className="text-xl font-bold text-[#0D1B3E] mt-2 leading-tight">{poster.title || poster.filename}</h2>
              </div>

              {/* User Authorship Info Card */}
              <div className="bg-[#f5f3f6] p-4 rounded-xl border border-[#DDE3EE] space-y-2">
                <p className="text-xs font-bold text-[#0D1B3E] uppercase tracking-wider flex items-center gap-1.5">
                  <User className="w-4 h-4 text-[#C0392B]" /> User Authorship & Session Specs
                </p>
                <div className="text-xs space-y-1 text-[#1b1b1e]">
                  <p>
                    <b className="text-[#0D1B3E]">Generated By User:</b> {poster.author}
                  </p>
                  {poster.authorEmail && (
                    <p>
                      <b className="text-[#0D1B3E]">User Email:</b> {poster.authorEmail}
                    </p>
                  )}
                  <p>
                    <b className="text-[#0D1B3E]">Template Used:</b> {poster.templateFolder || 'Standard Preset'}
                  </p>
                  <p>
                    <b className="text-[#0D1B3E]">Creation Date:</b> {poster.timeAgo}
                  </p>
                </div>
              </div>

              {/* Prompt / Campaign Specs */}
              <div className="bg-slate-50 p-4 rounded-xl border border-[#DDE3EE] space-y-2">
                <div className="flex justify-between items-center text-xs font-bold text-[#0D1B3E]">
                  <span className="flex items-center gap-1">
                    <Sparkles className="w-3.5 h-3.5 text-amber-500" /> Campaign Prompt & Specs
                  </span>
                  <button
                    onClick={handleCopyAlt}
                    className="text-[11px] text-[#1E3A6E] hover:underline flex items-center gap-1 cursor-pointer"
                  >
                    {copied ? <Check className="w-3 h-3 text-green-600" /> : <Copy className="w-3 h-3" />}
                    {copied ? 'Copied' : 'Copy Specs'}
                  </button>
                </div>
                <p className="text-xs text-slate-700 leading-relaxed italic">{poster.dataAlt}</p>
              </div>

              {/* Download / Bulk Specs */}
              {poster.isBulk && (
                <div className="bg-amber-50 border border-amber-200 p-3 rounded-xl text-xs text-amber-900 font-medium">
                  📦 <b>Bulk Job Archive:</b> Contains {poster.totalPostersInBulk || 'multiple'} generated poster images packaged into a single ZIP archive.
                </div>
              )}
            </div>

            {/* Actions */}
            <div className="flex flex-col gap-2 pt-4 border-t border-[#DDE3EE]">
              {poster.isBulk ? (
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  <button
                    onClick={() => downloadFile(poster.imageUrl, poster.filename)}
                    className="bg-[#1E3A6E] hover:bg-[#0D1B3E] text-white py-3 px-4 rounded-xl font-bold text-xs flex items-center justify-center gap-2 shadow-sm transition-all cursor-pointer"
                  >
                    <Download className="w-4 h-4" /> Download Poster Image
                  </button>

                  <button
                    onClick={() => downloadFile(poster.zipUrl || poster.imageUrl, poster.zipFilename || 'bulk_posters.zip')}
                    className="bg-[#C0392B] hover:bg-red-700 text-white py-3 px-4 rounded-xl font-bold text-xs flex items-center justify-center gap-2 shadow-sm transition-all cursor-pointer"
                  >
                    <FileArchive className="w-4 h-4" /> Download Complete Bulk ZIP
                  </button>
                </div>
              ) : (
                <div className="flex gap-3">
                  <button
                    onClick={() => onDownload(poster)}
                    className="flex-1 bg-[#0D1B3E] hover:bg-[#1E3A6E] text-white py-3 rounded-xl font-bold text-xs flex items-center justify-center gap-2 shadow-sm transition-all cursor-pointer"
                  >
                    <Download className="w-4 h-4" /> Download High-Res Poster
                  </button>
                  <button
                    onClick={handleCopyAlt}
                    className="px-4 bg-[#f5f3f6] hover:bg-[#eae7eb] text-[#0D1B3E] py-3 rounded-xl font-bold text-xs flex items-center justify-center gap-1 transition-all cursor-pointer"
                    title="Share & Copy"
                  >
                    <Share2 className="w-4 h-4" />
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
